spring:
  application:
    name: intro-to-spring-boot
  output:
    ansi:
      enabled: ALWAYS


server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
env:
  username: 'greywolf100'
  password: '#include<greyWolf100>'